#
# Makefile for the ActLinux-Beta board
#
# This file is subject to the terms and conditions of the GNU General Public
# License.  See the file "COPYING" in the main directory of this archive
# for more details.
#

obj-y	 := setup.o sdram.o
